name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - debug
  workflow_dispatch:

permissions:  # To publish to GitHub Pages
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install pyspelling
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling
    - name: Install aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Spell check
      run: |
        python -m pyspelling --config spellcheck/pyspelling_config.yml

  build:
    runs-on: ubuntu-latest
    needs: spell-check
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Debug
        run: |
          ls -lh
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
