name: Spell Check

on:
  push:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install pyspelling
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling
    - name: Install aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Spell check
      run: |
        python -m pyspelling --config spellcheck/pyspelling_config.yml